- README.md
- modules/json-schema/tests/src/StructureSpec.scala
- modules/openapi/src/internals/Hint.scala
- modules/openapi/src/internals/IModelToSmithy.scala
- modules/openapi/tests/src/OperationHeaderSpec.scala
- modules/openapi/tests/src/OperationSpec.scala
- modules/openapi/tests/src/ParameterSpec.scala
- modules/openapi/tests/src/StructureSpec.scala
Preserves name for structure members wherever possible. Where not possible, it will add a jsonName annotation.
> improves naming conversions for structure members

- README.md
- modules/proto/core/src/smithyproto/proto3/Compiler.scala
- modules/proto/core/src/smithyproto/proto3/MetadataProcessor.scala
- modules/proto/core/src/smithyproto/proto3/ModelPreProcessor.scala
- modules/proto/core/src/smithyproto/proto3/ProtoIR.scala
- modules/proto/core/src/smithyproto/proto3/Renderer.scala
- modules/proto/core/tests/src/CompilerRendererSuite.scala
- modules/proto/core/tests/src/CompilerSuite.scala
- modules/proto/core/tests/src/RendererSuite.scala
- modules/readme-validator/src/ReadmeParser.scala
- modules/readme-validator/src/Validator.scala
- modules/transitive/src/closure/IdRefVisitor.scala
- modules/transitive/src/closure/ModelOps.scala
- modules/transitive/src/closure/TransitiveModel.scala
- modules/transitive/tests/src/ClosureSpec.scala
- modules/transitive/tests/src/sample_specs.scala
The MetadataProcessor takes a model and extract a per namespace map of options. Before rendering a namespace we retrieve the options for a namespace and add them to the CompilationUnit.
Encoded as follows:
1. we use smithy metadata proto_options
2. we use an array of objects so that multiple proto_options can be concatenated
3. the options are defined per namespace
4. the options are String -> String
Regarding 4), I chose this encoding over String -> Any(bool, string, float, integer, identifier) because of the identifier.
You can do `option thing = "that";` but you can also do: `option thing = THAT;` where THAT would be a constant that protoc knows about.
To workaround the issue, the value is always a string, so if you want the former, you do `"thing": "\"that\""`, and if you want the …
> Introduce a way to add protoc options to protobuf definitions

- modules/json-schema/src/internals/Extractors.scala
- modules/json-schema/tests/src/EnumSpec.scala
Fixes an issue where JsonSchema enums with a type string field were being converted incorrectly.
> JsonSchema: fix string type enums

- README.md
- build.sc
- modules/proto/core/src/smithyproto/proto3/Compiler.scala
- modules/proto/core/tests/src/CompilerRendererSuite.scala
- modules/proto/examples/README.md
- modules/proto/examples/protobuf/demo/definitions.proto
- modules/proto/examples/smithy/demo.smithy
- smithy-build.json
If used more than once, throw
If unused, the shape is not exported
> Render union within message if used only once

- modules/json-schema/src/internals/Extractors.scala
- modules/json-schema/tests/src/MapSpec.scala
A json schema definition of an object with no explicit property but with `additionalProperties` set should convert to a smithy `map` definition.
With this change, the following definition
```json
{
"title": "foo",
"properties": {
"shouldBeAMap": {
"type": "object",
"additionalProperties": {
"type": "string"
}
}
}
}
```
will convert to
```smithy
structure Foo {
shouldBeAMap: ShouldBeAMap
}
structure ShouldBeAMap {
key: String
value: String
}
```
> convert object with additional  properties to smithy map

- modules/cli/src/opts/OpenAPIJsonSchemaOpts.scala
- modules/cli/src/runners/OpenApi.scala
- modules/cli/src/runners/openapi/ParseAndCompile.scala
- modules/cli/src/runners/openapi/ReportResult.scala
- modules/json-schema/src/JsonSchemaCompiler.scala
- modules/json-schema/tests/src/TestUtils.scala
- modules/openapi/src/OpenApiCompiler.scala
- modules/openapi/tests/resources/issue-23.json
- modules/openapi/tests/src/DebugSpec.scala
- modules/openapi/tests/src/TestUtils.scala
- modules/readme-validator/src/Validator.scala
Refs #23 
Currently, it only tweaks the validated result exception but
it could be used for other things. Current implementation rebuild
the exception with only DANGER and ERROR validation event when debug
is false. Which is the default.
It looks like this:
```
An error occurred while importing your Open API resources.
software.amazon.smithy.model.validation.ValidatedResultException: Result contained ERROR severity validation events:
[ERROR] issue_23#TestersGetTest: Operation URI, `/Testers/{id}`, conflicts with other operation URIs in the same service: [`issue_23#TestersGetTestTags` (/Testers/queries/unique-tags)] | HttpUriConflict N/A:0:0
[ERROR] issue_23#TestersGetTestTags: Operation URI, `/Testers/queries/unique-tags`, conflicts with other operation URIs in the same service: …
```
> Add a debug flag

- build.sc
- modules/cli/src/runners/Proto.scala
- modules/json-schema/src/internals/Extractors.scala
- modules/openapi/src/internals/IModelToSmithy.scala
- modules/proto/core/src/smithyproto/proto3/Compiler.scala
- modules/transitive/src/closure/IdRefVisitor.scala
Sorry for not being clear, the two are unrelated. I was doing maintenance work and realized that the scala version was outdated.
On top of that, I saw that we're using mill >= 0.10.8, which includes https://github.com/com-lihaoyi/mill/pull/1977/files which means we can get rid of `semanticDbVersion`
> Bump scala and get rid of the semanticDbVersion

- modules/formatter/src/ast/shapes.scala
- modules/formatter/src/parsers/ShapeParser.scala
- modules/formatter/src/writer/ShapeWriter.scala
- modules/formatter/tests/src/FormatterSpec.scala
- modules/formatter/tests/src/ParserSpec.scala
In this commit, we diverge from the specification. I've commented on a similar issue that was resolved a few days ago. My hopes are that a similar resolution is applied and the divergence is no more.
In short, the grammar states that a value assignment should look like this:
`ValueAssignment = *SP "=" *SP NodeValue BR`
But this BR is counter-intuitive and probably what's intended is a `*WS` which is what this commits implements.
This fixes formatter issues with Enum and Structure which both can define ValueAssignment on their members
> Fix enum support

- build.sc
- modules/formatter/parser-test/src/TestParser.scala
You can call it like so:
```
mill -w formatter.jvm.parser-test.run ~/path/to/specs/
```
> Add a module to run the parser on a folder recursively

- modules/formatter/parser-test/src/TestParser.scala
- modules/formatter/src/ast/node.scala
- modules/formatter/src/ast/shapes.scala
- modules/formatter/src/ast/whitespace.scala
- modules/formatter/src/parsers/NodeParser.scala
- modules/formatter/src/parsers/ShapeIdParser.scala
- modules/formatter/src/parsers/ShapeParser.scala
- modules/formatter/src/parsers/SmithyTraitParser.scala
- modules/formatter/src/parsers/WhitespaceParser.scala
- modules/formatter/src/parsers/package.scala
- modules/formatter/src/util/string_ops.scala
- modules/formatter/src/writer/NodeWriter.scala
- modules/formatter/src/writer/ShapeWriter.scala
- modules/formatter/src/writer/SmithyTraitWriter.scala
- modules/formatter/src/writer/WhiteSpaceWriter.scala
- modules/formatter/tests/src/FormatterSpec.scala
- modules/formatter/tests/src/ParserSpec.scala
1. diverge from the spec and support shape statement interspersed with BR rather than requiring a trailing BR 29167eb9beb68af5674075f9c7991d9fb049e85e
2. allow backtracking on optional value_assignment because otherwise the whitespace consumed is unavailable for the rest of the parsers 9ce027fea4b58c2dfddb3efe1dcc29e6bc04eada
3. tweak not_newline to support `///` and nothing else c5841b886f3228a3982b30aa2b0d3078f2302c08
4. allow mixins declaration with new lines in them (used when multiple mixin are used on one structure) e9758726c7422f54a229e5d61529fa9af237830d
5. tweak the operation parser to support operation input/output/errors out of order bf6c2da9ff76cf4ff4e919930216487f89696359
6. spacing around `=` in value assignment is optional: `*SP` f4678d1fe9cea59e7da3cfc590f6c3a76b7476fb
> Fix the last issues I found on the parser

- modules/openapi/src/internals/IModelToSmithy.scala
- modules/openapi/tests/src/StructureSpec.scala
- modules/openapi/tests/src/UnionSpec.scala
ShapeIds can only contain certain characters and still be valid. As such, this PR makes it so we will never create ShapeIds that contain invalid characters.
> sanitize names coming from openapi better

- modules/formatter/src/ast/shapeId.scala
- modules/formatter/src/ast/whitespace.scala
- modules/formatter/src/parsers/ShapeIdParser.scala
- modules/formatter/src/parsers/ShapeParser.scala
- modules/formatter/src/parsers/WhitespaceParser.scala
- modules/formatter/src/writer/ShapeWriter.scala
- modules/formatter/src/writer/WhiteSpaceWriter.scala
- modules/formatter/tests/src/FormatterSpec.scala
Support for comments is still not perfect. Following the grammar to the letter leads to an AST that has comments (things you'd like to keep) in weird places.
> Sort use statements, improve inline comment (w/ Break)

- modules/proto/core/src/smithyproto/proto3/Compiler.scala
- modules/proto/core/tests/src/CompilerSuite.scala
This fixes an issue where a smithy namespace of `com.EXAMPLE` was leading to a proto file called `e_x_a_m_p_l_e.proto` being created. There are a few other edge cases that I addressed as well, see tests I add for more.
> update so proto file naming is more consistent

- modules/proto/core/src/smithyproto/proto3/ModelPreProcessor.scala
- modules/proto/core/tests/src/ModelPrePocessorSpec.scala
- modules/traits/src/smithytranslate/BigDecimal.java
- modules/traits/src/smithytranslate/BigInteger.java
- modules/traits/src/smithytranslate/Timestamp.java
When using `model.getShape` with a shapeId and relying on whether or the shape is there, we risk not finding shapes because of a bad shape id.
In this case, smithy.api#Timestamp does not exist, so the timestamp shape was never _used_ according to this logic. This resulted in the output protobuf models not having the smithytranslate.timestamp message exported
> Use toSet(clazz) to find shapes

- modules/formatter/src/writer/ShapeWriter.scala
- modules/formatter/tests/src/FormatterSpec.scala
Mixins list can be separated by new line, in that
case we can remove the trailing comma to be more
more consistent with the rest of the formatting
Feedback from https://github.com/awslabs/smithy-language-server/pull/89
> Remove trailing comma when using newline

- build.sc
- modules/openapi/src/internals/GetExtensions.scala
- modules/openapi/src/internals/Hint.scala
- modules/openapi/src/internals/IModelToSmithy.scala
- modules/openapi/src/internals/OpenApiToIModel.scala
- modules/openapi/tests/src/ExamplesSpec.scala
- modules/openapi/tests/src/TestUtils.scala
Uses the `example` property from OpenAPI to fill in the `alloy#dataExamples` trait during the OpenAPI => Smithy conversion.
See the tests in this PR for more details.
> data examples trait in openapi conversion

- .scala-steward.conf
For some reason I did not realize that we use mill here and and build.sbt is invalid.
I realized that while integration testing something in scala-steward and using this repo as a test!
> Fix scala-steward config

- modules/json-schema/src/internals/Extractors.scala
- modules/json-schema/tests/src/PrimitiveSpec.scala
- modules/json-schema/tests/src/RefSpec.scala
- modules/json-schema/tests/src/StructureSpec.scala
The following JSON schema should translate to a Smithy `document` primitive.
```json
{
"$id": "test.json",
"$schema": "http://json-schema.org/draft-07/schema#",
"title": "FreeForm",
"type": "object",
"additionalProperties": true
}
```
The OpenApi translation already converts these types of definitions to freeform documents. See https://github.com/disneystreaming/smithy-translate/blob/v0.3.5/modules/openapi/src/internals/Extractors.scala#L46-L57
> JSON schema object with only additional properties should translate to freeform primitive

- modules/proto/core/src/smithyproto/proto3/Namespacing.scala
- modules/proto/core/tests/src/CompilerRendererSuite.scala
- modules/proto/core/tests/src/CompilerSuite.scala
- modules/proto/examples/protobuf/demo/common/definitions.proto
- modules/proto/examples/protobuf/demo/definitions.proto
- modules/proto/examples/smithy/common.smithy
- modules/proto/examples/smithy/demo.smithy
Prior, the files for a namespace like `foo.bar.baz` were output to `/foo/bar/baz.proto` however, they should be output to `/foo/bar/baz/definitions.proto` as to avoid collisions and generally unexpected behavior.
> fix so proto files are output to correct folders

- build.sc
- modules/cli/src/Main.scala
- modules/cli/src/SmithyBuildJsonWriter.scala
- modules/cli/src/opts/OpenAPIJsonSchemaOpts.scala
- modules/cli/src/opts/ProtoOpts.scala
So that when you open your editor in the folder, you don't get missing definitions for alloy and smithytranslate#contentType for example
> Dumo pre-configured smithy-build.json after translation

- modules/openapi/src/internals/Hint.scala
- modules/openapi/src/internals/IModelToSmithy.scala
- modules/openapi/src/internals/OpenApiToIModel.scala
- modules/openapi/src/internals/ParseOperations.scala
Closes #162 
There is indeed no other way but providing a dummy description in here, which is a bit annoying.
> Render dummy description in external docs for openapi->smithy

- modules/formatter/src/ast/shapes.scala
- modules/formatter/src/parsers/ShapeParser.scala
- modules/formatter/tests/src/FormatterSpec.scala
The IDL says: `"{" [WS] 1*(EnumShapeMember [WS]) "}"` which means atleast one member is required. In this case, I've allowed the implementation to drift from the spec because I don't think the parser should be validating business rules like that. From our point of view, it's hard to tell if the enum is empty when mixins could be adding members or not.
Fixes #171
> Allow empty enum

- README.md
- modules/json-schema/src/internals/JsonSchemaToIModel.scala
- modules/json-schema/tests/src/AllOfSpec.scala
- modules/openapi/src/internals/Hint.scala
- modules/openapi/src/internals/IModelToSmithy.scala
- modules/openapi/src/internals/postprocess/AllOfTransformer.scala
- modules/openapi/src/internals/postprocess/SimplifyNameTransformer.scala
- modules/openapi/src/internals/postprocess/TaggedUnionTransformer.scala
- modules/openapi/tests/src/AllOfSpec.scala
- modules/openapi/tests/src/TestUtils.scala
- modules/openapi/tests/src/UnionSpec.scala
Updates so that allOfs from OpenApi/JsonSchema are converted into smithy structures with mixins for the parents when possible/applicable. See the readme in the PR for full documentation on what this looks like.
Closes #107.
> Translate anyOfs to mixins where possible

- modules/openapi/src/internals/postprocess/ExternalMemberRefTransformer.scala
While reviewing, I found it a bit difficult to read when the pattern match was broken into multiple line so I checked it out to try and improve it. This is maybe overkill but it works well in this use case, let me know what you think
> Add some helper to extract from list

- modules/openapi/src/internals/IModelPostProcessor.scala
- modules/openapi/src/internals/postprocess/ExternalMemberRefTransformer.scala
- modules/openapi/tests/src/MultiFileSpec.scala
Fixes case where an external reference is pointing to a member shape targeting a primitive type.
> fix handling of external refs targeting member shapes

- modules/json-schema/src/internals/Extractors.scala
- modules/json-schema/src/internals/JsonSchemaToIModel.scala
- modules/json-schema/tests/src/RefSpec.scala
Per the JSON Schema spec, the ID field [is optional](https://json-schema.org/draft/2020-12/json-schema-core#name-the-id-keyword).
> JSON Schema Optional id Field

- modules/json-schema/src/internals/JsonSchemaToIModel.scala
- modules/json-schema/tests/src/RefSpec.scala
In older versions of json schema, `definitions` was used instead of `$defs`
> Support definitions for older json schema versions

- modules/openapi/src/internals/GetExtensions.scala
- modules/openapi/tests/src/TimestampSpec.scala
> Fix handling of date fields with examples

- modules/proto/src/smithyproto/proto3/ModelPreProcessor.scala
- modules/proto/tests/src/ModelPrePocessorSpec.scala
The gist of it is that we look for enum members are dupplicated
inside one namespace but we use a map[string, boolean], (equivalent
to a set[string]) to check for duplicates
the map should be keyed by `$namespace-$memberName`, not just `memberName`
the issue is that depending on the order of the processing, we can
override some keys in the map if other namespace have enum members
with the same name. in theory it should not be a problem, but my
implementation was wrong so it turned out to be a problem
-------
At HEAD, fixed:
```
> git log -1 --oneline 
a879ff9 (HEAD -> dfrancoeur/fix-enum-conflicts) Fix the prevent enum conflict algorithm
David.Francoeur@MAC-W1459R ~/w/d/smithy-translate (dfrancoeur/fix-enum-conflicts)> mill proto[2.13.12].tests.testOnly …
```
> Fix the prevent enum conflict algorithm 

- buildDeps.sc
- buildSetup.sc
- modules/cli/src/runners/Proto.scala
- modules/openapi/tests/src/DebugSpec.scala
- modules/proto/src/smithytranslate/proto3/internals/Compiler.scala
- modules/proto/tests/src/smithytranslate/proto3/internals/CompilerRendererSuite.scala
Adding support for protoTimestampFormat trait. Depends on https://github.com/disneystreaming/alloy/pull/149
> timestamp format for proto

- modules/proto/tests/src/smithytranslate/proto3/internals/ProtocInvocationHelper.scala
There was an issue where on some systems the resource lookup would find proto files in jar dependencies and would then attempt to treat them like local files. This fix makes it so jar dependencies are filtered out in our lookup.
> fix proto test nondeterminism

- mill
- modules/transitive/src/closure/TransitiveModel.scala
- modules/transitive/tests/src/ClosureSpec.scala
Uses `disableValidation` on the assembler rather than using the Model builder to disable validation. The model builder has other differences to the assembler that cause unexpected behavior, such as automatically omitting the prelude shapes with no option to include them.
> update how transitive module builds models

- .github/workflows/ci.yml
Same reason as https://github.com/disneystreaming/alloy/pull/187, the new secret no longer uses a passphrase
> remove pgp passphrase

- buildDeps.sc
- buildSetup.sc
- modules/cli/src/SmithyBuildJsonWriter.scala
- modules/proto-examples/README.md
- smithy-build.json
Now that we have the `com.disneystreaming` org available in Sonatype, this reverts to use it once again.
> revert org change

- buildDeps.sc
- buildSetup.sc
- modules/cli/src/opts/FormatterOpts.scala
- modules/cli/src/opts/OpenAPIJsonSchemaOpts.scala
- modules/cli/src/opts/ProtoOpts.scala
- modules/proto/src/smithytranslate/proto3/internals/Compiler.scala
- modules/proto/test/src/smithytranslate/proto3/internals/CompilerRendererSuite.scala
- modules/proto/test/src/smithytranslate/proto3/internals/CompilerSuite.scala
Update Alloy version to 0.3.28.
I updated Alloy to version 0.3.28, which came with some Prototbuf timestamp trait changes.  In particular, `alloy.proto#protoCompactOffsetDateTime` has been removed in favor of `alloy.proto#protoOffsetDateTimeFormat("PROTOBUF")`.
I updated the implementation in `Compiler` in two ways:
1. `TimestampFormat.RFC3339_STRING` needed a case in the `typeVisitor#timestampShape` function, which I set to use `String` values since it's being represented as a String date
2. `hasProtoCompact` now references the value in `protoOffsetDateTimeFormat` instead of checking for the `protoCompactOffsetDateTime` trait.  I was also having issues trying to narrow down a bug with the `hasProtoCompact` function so I moved it into the companion object to also make it more test-able
I …
> Update Alloy version to 0.3.28 and fix Protobuf timestamp implementations
